version: 2
jobs:
    run:
        docker:
            - image: circleci/node:carbon
        steps:
            - checkout
            - run: npm i
            - run: npm start
workflows:
    version: 2
    run:
        jobs:
            - run
    nightly:
        triggers:
            - schedule:
                  cron: '0 0 * * *'
                  filters:
                      branches:
                          only:
                              - master
        jobs:
            - run
