version: 2
jobs:
    build:
        docker:
            - image: circleci/node:carbon
        steps:
            - checkout
            - run: npm i
    run:
        docker:
            - image: circleci/node:carbon
        steps:
            - checkout
            - run: npm start
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - run
